app: # App
  pagination:
    limit:
      default: ${PAGINATION_LIMIT_DEFAULT:20}
      max: ${PAGINATION_LIMIT_MAX:100}
server:
  port: 8080
  servlet:
    context-path: /api/v1
springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    url: /api/v1/v3/api-docs.yaml
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'
    default-property-inclusion: NON_NULL
    serialization:
      write-dates-as-timestamps: false
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        show_sql: false
        use_sql_comments: false
